services:
  audio-legacy:
    runtime: nvidia
    environment:
      DEVICE: cuda
      NVIDIA_VISIBLE_DEVICES: all

  audio-kokoro:
    runtime: nvidia
    environment:
      DEVICE: cuda
      NVIDIA_VISIBLE_DEVICES: all

  audio-melotts:
    runtime: nvidia
    environment:
      DEVICE: cuda
      NVIDIA_VISIBLE_DEVICES: all

  audio-outetts:
    runtime: nvidia
    environment:
      DEVICE: cuda
      NVIDIA_VISIBLE_DEVICES: all

  audio-espnet:
    runtime: nvidia
    environment:
      DEVICE: cuda
      NVIDIA_VISIBLE_DEVICES: all

  audio-bark:
    runtime: nvidia
    environment:
      DEVICE: cuda
      NVIDIA_VISIBLE_DEVICES: all

  audio-chatterbox:
    runtime: nvidia
    environment:
      DEVICE: cuda
      NVIDIA_VISIBLE_DEVICES: all

  audio-fish-speech:
    runtime: nvidia
    environment:
      DEVICE: cuda
      FISH_SPEECH_DEVICE: cuda
      NVIDIA_VISIBLE_DEVICES: all
